		<tr>
			<td></td>
	        <td><a href="{root_path}/kunden/update/{customer[customerid]}" class="btn btn-primary btn-sm">Eintrag bearbeiten</a></td>
		</tr>
		<tr>
			<td>Kd.-Nr.</td>
	        <td>{customer[customerid]}</a></td>
		</tr>
		<tr>
			<td>Vorname</td>
	        <td>{customer[firstname]}</td>
		</tr>
		<tr>
			<td>Nachname</td>
	        <td>{customer[lastname]}</td>
		</tr>
		<tr>
			<td>Adresse 1</td>
	        <td>{customer[address1]}</td>
		</tr>
		<tr>
			<td>Adresse 2</td>
	        <td>{customer[address2]}</td>
		</tr>
		<tr>
			<td>Stadt</td>
	        <td>{customer[city]}</td>
		</tr>
		<tr>
			<td>Bundesstaat</td>
	        <td>{customer[state]}</td>
		</tr>
		<tr>
			<td>PLZ</td>
	        <td>{customer[zip]}</td>
		</tr>
		<tr>
			<td>Land</td>
	        <td>{customer[country]}</td>
		</tr>
		<tr>
			<td>Region</td>
	        <td>{customer[region]}</td>
		</tr>
		<tr>
			<td>E-Mail</td>
	        <td>{customer[email]}</td>
		</tr>
		<tr>
			<td>Telefon</td>
	        <td>{customer[phone]}</td>
		</tr>
		<tr>
			<td>Kreditkartentyp</td>
	        <td>{customer[creditcardtype]}</td>
		</tr>
		<tr>
			<td>Kreditkarte</td>
	        <td>{customer[creditcard]}</td>
		</tr>
		<tr>
			<td>Kreditkarte g&uuml;ltig</td>
	        <td>{customer[creditcardexpiration]}</td>
		</tr>
		<tr>
			<td>Benutzername</td>
	        <td>{customer[username]}</td>
		</tr>
		<tr>
			<td>Passwort</td>
	        <td>{customer[password]}</td>
		</tr>
		<tr>
			<td>Alter</td>
	        <td>{customer[age]}</td>
		</tr>
		<tr>
			<td>Einkommen</td>
	        <td>{customer[income]}</td>
		</tr>
		<tr>
			<td>Geschlecht</td>
	        <td>{customer[gender]}</td>
		</tr>